### ISSUE TITLE
Add docstrings to the functions generated by `get_strategies_namespace()`

### ISSUE THREAD

**Issue by mattip** [honno/hypothesis-array-api#1]
would be nice to have `help()` work

**Comment by honno** [comment]
For now I've just used `functools.update_wrapper()` to wrap the namespaced strategies. Once I put more work into the docstrings for the original methods there will be inconsistencies in the docstrings of the namespaced strategies (namely metnion of `xp` will be irrelevant)... and I think that'll have to be ok because otherwise I have to do some magic with docstrings which no one wants to see.
